### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by TomAdriaensen** [martip/node-red-google-apis#3]
Hi Paolo,

Thank you for making this node.
It could help us a lot connecting some Google products. I was thinking about creating users from a list in a spreadsheet.

I only get an error "Error: [object Object]"
Is there a way to display the error?

The Gsheet node works for us with the samen json key. But maybe I'm doing something wrong.

Thanks in advance,
Tom

**Comment by TomAdriaensen** [comment]
With some other functions I managed to get a better error. Is is possible to make an example to show how I have to use this? How should I pass the variables?

**Comment by martip** [comment]
> Hi Paolo,
> 
> Thank you for making this node. It could help us a lot connecting some Google products. I was thinking about creating users from a list in a spreadsheet.
> 
> I only get an error "Error: [object Object]" Is there a way to display the error?
> 
> The Gsheet node works for us with the samen json key. But maybe I'm doing something wrong.
> 
> Thanks in advance, Tom

Hi Tom, I improved the output of error messages in version 1.0.2.

**Comment by martip** [comment]
> With some other functions I managed to get a better error. Is is possible to make an example to show how I have to use this? How should I pass the variables?

You can use a function node to create a payload. The following example can be used to find Google Sheets files in a Google Drive folder;
```javascript
const folderId = '<some_drive_folder_id>';

msg.payload = {
    q: `'${folderId}' in parents and mimeType='application/vnd.google-apps.spreadsheet' and trashed = false`,
    fields: 'files(id, name)',
    spaces: 'drive',
    supportsAllDrives: true,
    includeItemsFromAllDrives: true
};

return msg;
```

Connect this function node to a `google-apis` node, configured with
* **API** `drive:v3`
* **Method** `files.list`.

The `google-apis-authentication` node must be configured with your [Google Service Account](https://cloud.google.com/iam/docs/service-accounts) JSON Key, similar to this one:

```json
{
  "type": "service_account",
  "project_id": "api-project-...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "...@api-project-....iam.gserviceaccount.com",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/....iam.gserviceaccount.com"
}
```

**Comment by TomAdriaensen** [comment]
Paolo,
Thank you for your help! It is much appreciated.
