### ISSUE TITLE
Credential Problem

### ISSUE THREAD

**Issue by Dannol0** [martip/node-red-google-apis#4]
Hi,

I had no issue using the node for API call using Google API V3.
My problem is related to  a security issue.
Since our node red project is going to be shared with other people, I would like to use a process variable loaded dinamically to get credential information for Google API.

As far as I have investigated, right now is not possible doing that because you can only put the JSON file in the configuration node.
Are you planning to make it possible?
Am I missing something to make it work correctly?

Let me know if I didn't explain well.

Nice job, btw :)

**Comment by martip** [comment]
Hi DannoIO,

working on it!
