### ISSUE TITLE
"TypeError: google[api.name] is not a function"

### ISSUE THREAD

**Issue by abdul-Tz-prog** [martip/node-red-google-apis#5]
Hello,

I really like the Node. but on selecting (dynamic) msg.api in API and method as (dynamic) msg.method. It always gives error :

**"TypeError: google[api.name] is not a function"**

<img width="226" alt="image" src="https://user-images.githubusercontent.com/85757348/216315620-b3578a6c-306b-467d-8ea1-fcfff822199a.png">

Can any one tell me what this error is occurring.

On the other hand if I select any API endpoint. It gives error. 

**msg : Object
{ empty }**

Any kind of help will be appreciated. :)

**Comment by martip** [comment]
Fixed, thank you.
